dataset_name: 'KITTI' 
dataset_path: '.' 
resize: [128, 256]

baseline_model: 'bls17'
use_side_info: True 
num_filters: 192 
cuda: False
load_weight: True
weight_path: './pretrained_weights/balle17+ours/KITTI/balle17+ours_MS-SSIM_lambda3e-05.pt' # weight path for loading

train: False
epochs: 50000
train_batch_size: 1
lr: 0.0001
lambda: 0.00003 
alpha: 1
beta: 1
verbose_period: 50
distortion_loss: 'MS-SSIM'

save_weights: True
save_output_path: './outputs'
experiment_name: 'bls17_with_side_info_MS-SSIM_lambda:3e-05'

test: True
save_image: True
